server:
  servlet:
    context-path: /serverapp1
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver